[project]
name = "calibration-cost-sensitive-learning"
version = "0.1.0"
description = "Repository for a course on calibration and cost-sensitive learning"
authors = ["Guillaume Lemaitre <guillaume@probabl.ai>", "Olivier Grisel <olivier@probabl.ai>"]
channels = ["conda-forge"]
platforms = ["win-64", "linux-64", "osx-64", "osx-arm64"]

[tasks]

[dependencies]
jupyterlab = ">=4.2.4,<5"
numpy = ">=2.0.1,<3"
scipy = ">=1.14.0,<2"
scikit-learn = ">=1.5.1,<2"
pandas = ">=2.2.2,<3"
matplotlib = ">=3.9.1,<4"

[feature.dev.dependencies]
ipykernel = "*"

[feature.lint.dependencies]
ruff = "*"
black = "*"

[environments]
lint = ["lint"]
dev = ["dev", "lint"]
