[project]
name = "calibration-cost-sensitive-learning"
version = "0.1.0"
description = "Add a short description here"
authors = ["Guillaume Lemaitre <guillaume@probabl.ai>"]
channels = ["conda-forge"]
platforms = ["osx-arm64"]

[tasks]

[dependencies]
