[project]
name = "calibration-cost-sensitive-learning"
version = "0.1.0"
description = "Probabilistic calibration of cost-sensitive learning"
authors = ["Guillaume Lemaitre <guillaume@probabl.ai>", "Olivier Grisel <olivier@probabl.ai>"]
channels = ["conda-forge"]
platforms = ["win-64", "linux-64", "osx-64", "osx-arm64"]

[tasks]
generate-predictions = { cmd = "python _generate_predictions.py", cwd = "content/python_files" }
build-calibration-curve = { cmd = "ipython build_calibration_curve.py", cwd = "content/python_files" }
check-generated-predictions = { cmd = "python check_generated_predictions.py", cwd = "tests" }
different-calibration-curves = { cmd = "ipython different_calibration_curves.py", cwd = "content/python_files" }
miscalibration-under-over-fit = { cmd = "ipython miscalibration_under_over_fit.py", cwd = "content/python_files" }
miscalibration-reweighting = { cmd = "ipython miscalibration_reweighting.py", cwd = "content/python_files" }
cost-sensitive-learning = { cmd = "ipython cost_sensitive_learning.py", cwd = "content/python_files" }

[dependencies]
jupyterlab = ">=4.2.4,<5"
numpy = ">=2.0.1,<3"
scipy = ">=1.14.0,<2"
scikit-learn = ">=1.5.1,<2"
pandas = ">=2.2.2,<3"
matplotlib = ">=3.9.1,<4"
jupytext = ">=1.16.4,<2"
pyarrow = ">=17.0.0,<18"

[feature.dev.dependencies]
ipykernel = "*"

[feature.lint.dependencies]
ruff = "*"
black = "*"

[feature.doc.dependencies]
jupyter-book = "*"

[feature.doc.tasks]
convert-to-notebooks = { cmd = "jupytext --to notebook ./content/python_files/*.py && mkdir -p ./content/notebooks && mv ./content/python_files/*.ipynb ./content/notebooks" }
convert-to-executed-notebooks = { cmd = "jupytext --to notebook --execute ./content/python_files/*.py && mkdir -p ./content/notebooks && mv ./content/python_files/*.ipynb ./content/notebooks" }
build-book = { cmd = "jupyter-book build book", depends-on = ["convert-to-notebooks"] }

[environments]
lint = ["lint"]
doc = ["doc"]
dev = ["dev", "doc", "lint"]
