[project]
name = "calibration-cost-sensitive-learning"
version = "0.1.0"
description = "Probabilistic calibration of cost-sensitive learning"
authors = ["Guillaume Lemaitre <guillaume@probabl.ai>", "Olivier Grisel <olivier@probabl.ai>"]
channels = ["conda-forge"]
platforms = ["win-64", "linux-64", "osx-64", "osx-arm64"]

[tasks]
generate-predictions = { cmd = "python _generate_predictions.py", cwd = "python_files" }
build-calibration-curve = { cmd = "ipython build_calibration_curve.py", cwd = "python_files" }
check-generated-predictions = { cmd = "python check_generated_predictions.py", cwd = "tests" }

[dependencies]
jupyterlab = ">=4.2.4,<5"
numpy = ">=2.0.1,<3"
scipy = ">=1.14.0,<2"
scikit-learn = ">=1.5.1,<2"
pandas = ">=2.2.2,<3"
matplotlib = ">=3.9.1,<4"
jupytext = ">=1.16.4,<2"

[feature.dev.dependencies]
ipykernel = "*"

[feature.lint.dependencies]
ruff = "*"
black = "*"

[environments]
lint = ["lint"]
dev = ["dev", "lint"]
