name: 'publish_book'

on:
  push:
    branches:
      - "main"

jobs:
  publish_book:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: prefix-dev/setup-pixi@v0.8.1
        with:
          pixi-version: v0.27.1
          environments: doc

      - name: Build and publish the book
        run: pixi run -e doc build-book

      - name: Update the main gh-page website
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book/_build/html
          commit_message: "[ci skip] ${{ github.event.head_commit.message }}"

