name: 'test'

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - '*'

jobs:
  test:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        environment: [default]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: prefix-dev/setup-pixi@v0.8.1
        with:
          pixi-version: v0.27.1
          environments: ${{ matrix.environment }}

      - name: Run tests
        run: |
            pixi run generate-predictions
            pixi run check-generated-predictions
            pixi run build-calibration-curve
            pixi run different-calibration-curves
            pixi run -e doc build-book